name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: integrator
          POSTGRES_PASSWORD: inteword
          POSTGRES_DB: locationservice
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      # Compile
      - name: Restore dependencies
        run: dotnet restore ./src/StatlerWaldorfCorp.LocationService --locked-mode

      - name: Build
        run: dotnet build ./src/StatlerWaldorfCorp.LocationService --no-restore

      # Unit tests
      - name: Unit Tests Restore
        run: dotnet restore ./test/StatlerWaldorfCorp.LocationService.Tests

      - name: Unit Tests Build
        run: dotnet build ./test/StatlerWaldorfCorp.LocationService.Tests --no-restore

      - name: Unit Tests Run
        run: dotnet test ./test/StatlerWaldorfCorp.LocationService.Tests --no-build --verbosity normal

      # Integration tests
      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef
        if: success() && matrix.config != 'net6.0'
      
      - name: Integration Migrate
        run: |
          export TRANSIENT=false
          export POSTGRES__CSTR="Host=localhost;Username=integrator;Password=inteword;Database=locationservice"
          dotnet ef database update
        working-directory: ./src/StatlerWaldorfCorp.LocationService

      - name: Integration Restore
        run: dotnet restore ./test/StatlerWaldorfCorp.LocationService.Tests.Integration

      - name: Integration Build
        run: dotnet build ./test/StatlerWaldorfCorp.LocationService.Tests.Integration --no-restore

      - name: Integration Test
        run: dotnet test ./test/StatlerWaldorfCorp.LocationService.Tests.Integration --no-build --verbosity normal

